### ISSUE TITLE
Uninstalling mess with tree view

### ISSUE THREAD

**Issue by yamsellem** [ddavison/sublime-tabs#54]
Uninstalling or disabling this plugin seems to break tree view which is no longer available (until reinstalling this plugin).

**Comment by ddavison** [comment]
In the [readme](https://github.com/ddavison/sublime-tabs#uninstall), and the [package readme](https://atom.io/packages/sublime-tabs), 

I notify the user that they need to reenable those packages.

[This was discussed previously](https://github.com/ddavison/sublime-tabs/issues/30) but did not go through because of the ambiguity between uninstalling, and just deactivating.

**Comment by yamsellem** [comment]
Ok. I miss that issue.
Close this one for duplicate.
